config:
  entryPoint: '/app.php'
  assetsDir: '/assets'
  debug: true
  cacheDir: '/cache'
security:
  checksumKeyFile: '66b7335d24862a3e204eec3c3622bb9a'
api:
  travis:
    url: 'https://api.travis-ci.org'
    imgUrl: '<a href="https://travis-ci.org/%s"><img alt="Build Status %s" src="https://travis-ci.org/%s.svg?branch=%s"></a>'
  scrutinizer:
    imgUrlCoverage: >
                      <a href = "https://scrutinizer-ci.com/g/%s/?branch=%s" >
                      <img src = "https://scrutinizer-ci.com/g/%s/badges/coverage.png?b=%s" alt = "Code Coverage %s" />
                      </a >
    imgUrlQuality: >
                     <a href="https://scrutinizer-ci.com/g/%s/?branch=%s">
                     <img src="https://scrutinizer-ci.com/g/%s/badges/quality-score.png?b=%s" alt="Scrutinizer Code Quality %s"/>
                     </a>
